### ISSUE TITLE
Downloading with diferent quality?

### ISSUE THREAD

**Issue by Dokman** [redbaty/Wasari#1]
it can be done? i usually use 1080p but another people use 720p it's possible?

**Comment by mvmcjr** [comment]
Certanly! Since we use yt-dlp to download our streams, this means any format supported by it can be used here.
I've now exposed an argument "-f" and for 720p it should be used like this: `-f "best[height=720]"`, more information can be found [here](https://github.com/yt-dlp/yt-dlp#filtering-formats)

**Comment by mvmcjr** [comment]
Available on build #37 and onwards.
